api_platform:
  title: API Platform
  version: 1.0.0
  # Good defaults for REST APIs
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
    enable_max_depth: true
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  eager_loading:
    max_joins: 10
